### ISSUE TITLE
EltonTraits vs mammalDIET choice and, are the converted ordinal diet values to percentages available? 

### ISSUE THREAD

**Issue by fabeit** [MegaPast2Future/PHYLACINE_1.2#1]
From what I understand diet values were chosen from Eltontraits if they had certainty ABC or mammalDIET if they had 0 or 1. But how did you pick from the two when a species had both ABC and 0/1 in their respective databases?

It would be very useful to have the converted ordinal to percentages as I am trying to estimate the percentage of plant parts consumed for each species. Do you also have the percentages for the species you determined directly, not from Eltontraits or mammalDIET?

Thank you

**Comment by ursus-americanus** [comment]
Hi @fabeit,
Thanks for using PHYLACINE. We only used mammalDIET values when a species was missing from EltonTraits. We don't have the individual percentage data you are requesting because we never converted each ordinal subcategory in mammalDIET to dietary percentages. We just compared the broad Plant, Invertebrate, and Vertebrate scores to a sum of percentages in EltonTraits for Plant, Invertebrate, and Vertebrate. I wouldn't recommend trying to convert really finely resolved mammalDIET data to finally resolved EltonTraits percentages. The categories don't quite match up and I bet that the correlations we found would start to fall apart. 

Unfortunately, we also don't have really detailed diet data for the species where we collected the diet data ourselves. It would certainly be useful but for many species, especially fossils, we really don't know what parts of the plant they consumed and in which proportions. You can look at the citations for diets in PHYLACINE, EltonTraits, and mammalDIET to track down the original sources. They will have more information. You can also check [The Handbook of the Mammals of the World](https://www.lynxeds.com/catalog/hmw). They are good for finding dense mammal diet data.

Let us know if you have any more questions!
