### ISSUE TITLE
Species from Phylacine not matching in MammalDiet

### ISSUE THREAD

**Issue by fabeit** [MegaPast2Future/PHYLACINE_1.2#2]
I have noticed that 20-30 species, whose diet was compiled with data from MammalDiet1 or 2, cannot be found in the MammalDiet database. 

For example Piliocolobus preussi is marked with "Transformed 000 Species" and diet.source mammDIET2 but this species/genus is not found in mammalDiet. Am I missing something?

There are also some species marked with Transformed 000 Genus that are not found in the database. Is this expected since the diet in Phylacine is compiled using the genus average?

**Comment by jarsc568** [comment]
Hi @fabeit 
Thanks for your continued use of PHYLACINE. Regarding taxonomic differences, we note that the databases we referred to as "MammalDIET" and "MammalDIET 2" do not always follow the taxonomy as provided in PHYLACINE v 1.2 as this was based on IUCN v 2016-3 (the other databases were not necessarily the same). The taxonomic differences, however, should be able to be found in the synonymy tables in the Taxonomy folder. We think differences between "MammalDiet 2" and PHYLACINE v 1.2 should be:

Binomial | Binomial.1.2
-- | --
Tadarida_kuboriensis | Austronomus_kuboriensis
Cebus_cay | Sapajus_cay
Cebus_flavius | Sapajus_flavius
Cercopithecus_lhoesti | Allochrocebus_lhoesti
Cercopithecus_preussi | Allochrocebus_preussi
Lepilemur_tymerlachsonorum | Lepilemur_tymerlachsoni
Pithecia_irrorata | Pithecia_vanzolinii
Pithecia_monachus | Pithecia_milleri
Procolobus_gordonorum | Piliocolobus_gordonorum
Procolobus_pennantii | Piliocolobus_pennantii
Procolobus_preussi | Piliocolobus_preussi
Liomys_adspersus | Heteromys_adspersus
Orthogeomys_cherriei | Heterogeomys_cherriei
Spermophilus_beecheyi | Otospermophilus_beecheyi
Spermophilus_canus | Urocitellus_canus
Spermophilus_elegans | Urocitellus_elegans
Spermophilus_franklinii | Poliocitellus_franklinii
Spermophilus_spilosoma | Xerospermophilus_spilosoma
Spermophilus_tereticaudus | Xerospermophilus_tereticaudus
Spermophilus_undulatus | Urocitellus_undulatus
Tamias_dorsalis | Neotamias_dorsalis
Tamias_durangae | Neotamias_durangae
Tamias_merriami | Neotamias_merriami
Tamias_senex | Neotamias_senex
Tamias_umbrinus | Neotamias_umbrinus
Lutra_maculicollis | Hydrictis_maculicollis
Pseudalopex_fulvipes | Lycalopex_fulvipes
Pseudalopex_griseus | Lycalopex_griseus
Pseudalopex_sechurae | Lycalopex_sechurae
Ochotona_pallasi | Ochotona_pallasii
Orthogeomys_dariensis | Heterogeomys_dariensis
Spermophilus_armatus | Urocitellus_armatus
Spermophilus_madrensis | Callospermophilus_madrensis
Pipistrellus_savii | Hypsugo_savii
Myotis_bocagei | Myotis_bocagii
Stenonycteris_lanosus | Rousettus_lanosus
Pygathrix_brelichi | Rhinopithecus_brelichi
Marmosa_phaeus | Marmosa_phaea

In addition, we made the following changes between MammalDiet and PHYLACINE: 
“Myotis_bocagei” which we call "Myotis_bocagii"
"Stenonycteris_lanosus" which we call "Rousettus_lanosus"
"Pygathrix_brelichi" which we call "Rhinopithecus_brelichi"
"Marmosa_phaeus" which we call "Marmosa_phaea"

To use your example of _Piliocolobus preussi_, note that it is in earlier versions of the taxonomy and in MammalDiet 2 it is known under the _Procolobus preussi_. Once you have checked if differences are due to changed synonymy between databases, and there continue to be inconsistencies, do send your list of species through for us to investigate further. 

In terms of the question on regarding genus level, the metadata addresses this where it states: "Less frequently, diet could be determined at the genus level but only when the authors of these original databases expertly judged all species in a genus to have similar diet, e.g. refererence said, "the genus is completely herbivorous""

**Comment by fabeit** [comment]
Hi @jarsc568 
Thank  you for the clarification. So if I understand correctly, to find synonyms with other datasets that are not Elton traits, I have to scan all previous versions of Phylacine Binomials (1.1 and 1.0) in the synonym table?
May I suggest that since your data is tightly coupled with MammalDiet, it would be useful to have two dedicated columns for the synonyms in MammalDiet genus and species, just like you have with the Elton traits synonyms.
I will report back any inconsistencies.

**Comment by jarsc568** [comment]
Hi @fabeit 
No worries. Regarding the taxonomy, for extant species we followed IUCN v 2016-3 except for some extremely poorly known species we judged unlikely to be valid. Excluded species and justifications can be found in Synonymy_table_with_unaccepted_species.csv. Taxonomy of fossil species mostly followed Sandom et al. 2014. See the metadata in the Ecology for more information. As the species names you may using could be different, you may have to check for synonyms, either in PHYLACINE Binomials 1.0 or 1.2 or perhaps elsewhere. One place to find synonyms could be by using the Taxize package in R, but I'm sure there are many other places you can look. Hope this helps for clarification. 
Thanks for your suggestion of the dedicated columns for MammelDiet. We will consider it when we start work on the next major update. If in the meantime you would like to fork the repository and add the dedicated columns, please feel free.
Will be great to receive any inconsistencies. Thanks.
