### ISSUE TITLE
Body mass error for Equus africanus

### ISSUE THREAD

**Issue by ejlundgren** [MegaPast2Future/PHYLACINE_1.2#4]
Dear Phylacine team,

I noticed today that Equus africanus is listed as having a body mass of 325000g in your trait database. The resource in Smith et al. (the ref) does not have E. africanus but has 164998.5g for E. asinus (E. africanus' post domestic). I haven't been able to find any actual data sources for the african wild ass' mass, so perhaps I am missing something. 

Many thanks and happy new year,

Erick

**Comment by rasmus87** [comment]
Dear Eric

Thank you for noticing our discrepancy. I looked into it, and MOM actually listed two values for Equus asinus, one for Africa as you quote, and one for the introduced population in Australia. The PHYLACINE  weight matches the Australian one, I don't know why that happened.
We have decided to switch resource for this species to _Handbook of the Mammals of the World_ instead, which refers to a body mass between the two values. It is 270-280 kg, which we will list as 275 kg in the upcoming minor update, unless you have a better resource?

Rasmus

**Comment by ejlundgren** [comment]
Dear Rasmus,

That's strange! 275kg still seems big to me, as it is larger than the mass for Equus ferus (250kg) - unless Przewalski's horse is really smaller than a donkey? AnAge Database (http://genomics.senescence.info/species/) has 164,998, which allies with the Smith dataset I have. However that seems like it could be low - as the asiatic ass, Equus hemionus is listed as 230kg. 

This is definitely confusing! What does the Handbook say for E ferus and E hemionus?

Thanks for looking into this!

Erick

**Comment by fabeit** [comment]
I have to say that going through many species in the database I have noticed some discrepancies for some species larger than 10kg, some primates and some extinct species. I didn't report any of them because it was within the same order of magnitude and I would always expect some discrepancies based on the source.

**Comment by ejlundgren** [comment]
Dear Rasmus,

I've now checked with Walker's Mammals of the World.

They list Przewalski as 250kg; Equus caballus as 530kg; Equus africanus/asinus as 250kg.

The other equid body masses in Walker's match Phylacine. 

Hard to know what to do when there's so much discrepancy! Thanks for considering all of this.

Erick

**Comment by rasmus87** [comment]
I think the reason for these discrepancies are the "over-certainty" there are being put on the exact values. The truth for many of the body mass estimates is that they are likely based on one individual, and are not population means. In an ideal world we would of course love to have population body mass mean and spread for all species - which is not possible. But we do try in some cases. Measurements of individuals, as well as differences between populations, domestic vs non-domestic, bread and wild can probably give widely different estimates. This will probably as with the horses give some weird estimates between closely related species within a genus. Which we have to think about how we should handle.
That said - I also think that these are the best available data easily obtained for as many species as possible, and is not bad or biased across the data-set.

We will discuss the use of either _Walker's mammals of the world_ or the _Handbook of the Mammals of the World_ estimates for these species. Maybe it is best to stick to one source. We will get back to you on this unless you have a good argument for using one source rather than the other.

**Comment by ejlundgren** [comment]
@rasmus87 - I completely understand that there's always going to be a degree of 'slop' with these estimates! There's no way for a single number accurately represent a species. Thank you for looking into this!
